const fs=require('fs'),http=require('http'),assert=require('assert/strict');const{chromium}=require('C:/Users/dangq/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
(async()=>{const server=http.createServer((q,r)=>{r.setHeader('Content-Type','text/html; charset=utf-8');r.end(fs.readFileSync('index.html'))});await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({headless:true,channel:'msedge'}),checks=[];
try{for(const width of [390,1366]){const p=await browser.newPage({viewport:{width,height:1000},reducedMotion:'reduce'}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.route('**/*',r=>r.request().url().startsWith('http://127.0.0.1:')?r.continue():r.abort());await p.goto('http://127.0.0.1:'+server.address().port);await p.addStyleTag({content:'*,*::before,*::after{animation:none!important;transition:none!important}'});
const sample=await p.evaluate(()=>{const q=prepareQuestion(BANKS.b1[0](),'b1',0),values=q.blanks.map(b=>String(b.a));values[0]='999';values[1]='con viết nhầm';values[2]='';quizQs=[q];quizHistory=[{idx:1,userAnswer:values.join('|'),correctAnswer:q.a,reviewAnswer:q.a,reviewCorrect:true,isCorrect:false}];showSummary();return{values,solution:q.blanks.map(b=>String(b.a))};});
async function open(){await p.locator('#parent-results-btn').click();await p.locator('#parent-results-password').fill('452012');await p.locator('#parent-results-dialog button[type=submit]').click();await p.locator('#summary-table-body > .row > .q > details > summary').click();}
await open();assert.deepEqual(await p.locator('.comparison-submitted .summary-answer-text').allTextContents(),sample.values.map(x=>x||'—'));assert.deepEqual(await p.locator('.comparison-solution .summary-answer-text').allTextContents(),sample.solution);assert.equal(await p.locator('.comparison-submitted input').count(),0);assert.equal(await p.locator('.comparison-submitted .snapshot-wrong').count(),2);
const first=await p.locator('.comparison-submitted').boundingBox(),second=await p.locator('.comparison-solution').boundingBox();assert.ok(second.y>first.y+first.height);
await p.locator('.comparison-submitted .tbl-wrap').evaluate(el=>el.scrollLeft=el.scrollWidth);await p.waitForTimeout(100);const scroll=await p.locator('.comparison-solution .tbl-wrap').evaluate(el=>el.scrollLeft);assert.ok(scroll>0);
await p.locator('.comparison-submitted').scrollIntoViewIfNeeded();await p.screenshot({path:'.audit/comparison-'+width+'.png'});await p.locator('.comparison-solution').screenshot({path:'.audit/comparison-solution-'+width+'.png'});
await p.evaluate(()=>{const builder=Q(1,'Chọn đáp án và điền dấu');const body=builder.pick('A,C',['A','B','C'])+builder.sign('>')+builder.num(42);const q=prepareQuestion(builder.done(body),'b1',0);quizQs=[q];quizHistory=[{idx:1,userAnswer:'B|<|<img src=x onerror=alert(1)>',correctAnswer:q.a,isCorrect:false}];showSummary();});await open();
assert.deepEqual(await p.locator('.comparison-submitted .pk.on').allTextContents(),['B']);assert.deepEqual(await p.locator('.comparison-solution .pk.on').allTextContents(),['A','C']);assert.equal(await p.locator('.comparison-submitted .qsign').innerText(),'<');assert.equal(await p.locator('.comparison-solution .qsign').innerText(),'>');assert.equal(await p.locator('.comparison-panel img').count(),0);assert.equal(await p.locator('.comparison-submitted .summary-answer-text').innerText(),'<img src=x onerror=alert(1)>');
await p.evaluate(()=>startQuiz('b1'));await p.locator('#q-body input').first().fill('123');await p.keyboard.press('Control+ArrowRight');assert.equal(await p.evaluate(()=>quizHistory[0].userAnswer.split('|')[0]),'123');assert.equal(await p.evaluate(()=>quizHistory[0].skipped),true);
assert.deepEqual(errors,[]);checks.push({width,originalPreserved:true,correctValues:true,stacked:true,scrollLinked:true,picksAndSigns:true,safeText:true,partialSkipPreserved:true});await p.close();}}finally{await browser.close();server.close();}fs.writeFileSync('.audit/comparison-results.json',JSON.stringify(checks,null,2));console.log(JSON.stringify(checks,null,2));})().catch(e=>{console.error(e);process.exit(1)});
