const fs=require('fs'),http=require('http'),assert=require('assert/strict');const{chromium}=require('C:/Users/dangq/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
(async()=>{const server=http.createServer((q,r)=>{r.setHeader('Content-Type','text/html; charset=utf-8');r.end(fs.readFileSync('index.html'))});await new Promise(r=>server.listen(0,'127.0.0.1',r));const b=await chromium.launch({headless:true,channel:'msedge'}),p=await b.newPage({viewport:{width:390,height:844},reducedMotion:'reduce'});const errors=[];p.on('pageerror',e=>errors.push(e.message));p.on('dialog',d=>d.type()==='prompt'?d.accept('452012'):d.accept());await p.route('**/*',r=>r.request().url().startsWith('http://127.0.0.1:')?r.continue():r.abort());const url='http://127.0.0.1:'+server.address().port;await p.goto(url);const checks=[];
async function unlockResults(){await p.locator('#parent-results-btn').click();await p.locator('#parent-results-password').fill('452012');await p.locator('#parent-results-dialog button[type="submit"]').click();}
await p.evaluate(()=>startQuiz('b2'));await p.evaluate(()=>{subs=currentQ.blanks.map(x=>x.a);paint()});await p.locator('#q-body .qin').last().press('Enter');assert.equal(await p.evaluate(()=>qIndex),1);assert.equal(await p.evaluate(()=>quizHistory.length),1);checks.push('Enter submits exactly one question');
await p.evaluate(()=>{S.lastDay='Mon Jan 01 2024';S.streak=30;refreshHeader();renderProfile()});assert.equal(await p.locator('#r-streak').innerText(),'0');assert.equal(await p.evaluate(()=>BADGES.find(x=>x.t==='3 ngày liền').need(S)),false);checks.push('expired streak is not shown or awarded');
const preserved=await p.evaluate(()=>{const d={done:['b2','b2','b999'],doneAdv:['b18'],stars:100,totalQ:10,totalCorrect:7,streak:2,lastDay:dayLabel()};localStorage.setItem('bb3_state',JSON.stringify(d));return d});await p.reload();assert.deepEqual(await p.evaluate(()=>({done:S.done,adv:S.doneAdv,stars:S.stars,total:S.totalQ,correct:S.totalCorrect})),{done:['b2'],adv:['b18'],stars:100,total:10,correct:7});checks.push('legacy progress migrates without losing valid values');
await p.evaluate(()=>goMap());const head=p.locator('.island-head').first();await head.focus();await head.press('Enter');assert.equal(await head.getAttribute('aria-expanded'),'false');await head.press('Space');assert.equal(await head.getAttribute('aria-expanded'),'true');checks.push('lesson groups work with keyboard');
await p.evaluate(()=>openSettings());assert.equal(await p.locator('#input-parental-pass').evaluate(x=>x===document.activeElement),true);await p.keyboard.press('Escape');assert.equal(await p.locator('#settings-modal').evaluate(x=>x.classList.contains('show')),false);checks.push('settings focuses input and closes with Escape');
await p.evaluate(()=>{const q=prepareQuestion(BANKS.b1[1](),'b1',1);quizQs=[q];quizHistory=[{idx:1,question:q.q,userAnswer:q.a,correctAnswer:q.a,isCorrect:true}];showSummary();});await unlockResults();await p.locator('#summary-table-body summary').click();await p.waitForTimeout(100);assert.equal(await p.locator('.summary-lines path').count(),8);assert.equal(await p.locator('.summary-question [id]').count(),0);await p.screenshot({path:'.audit/fixed-summary.png'});checks.push('review diagrams retain all four connections in each comparison without duplicate IDs');
await p.evaluate(()=>{localStorage.setItem('bb3_state','{bad')});await p.reload();await p.evaluate(()=>startQuiz('b18'));await p.waitForTimeout(100);const fit=await p.locator('#quiz-screen').evaluate(x=>({bottom:x.getBoundingClientRect().bottom,viewport:innerHeight}));assert.ok(fit.bottom<=fit.viewport+1);checks.push('recovery notice does not hide quiz bottom');
await p.evaluate(()=>startLesson('b1'));assert.match(await p.locator('#video-source').innerText(),/Bài giảng/);assert.equal(await p.locator('#video-start-btn').isEnabled(),true);checks.push('lesson video identifies its source and practice remains available');
assert.deepEqual(errors,[]);fs.writeFileSync('.audit/edge-results.json',JSON.stringify({passed:checks.length,checks,errors},null,2));console.log(JSON.stringify({passed:checks.length,checks,errors},null,2));await b.close();server.close();})().catch(e=>{console.error(e);process.exit(1)});
