const fs=require('fs'),http=require('http'),assert=require('assert/strict');const{chromium}=require('C:/Users/dangq/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
(async()=>{const server=http.createServer((q,r)=>{r.setHeader('Content-Type','text/html; charset=utf-8');r.end(fs.readFileSync('index.html'))});await new Promise(r=>server.listen(0,'127.0.0.1',r));const b=await chromium.launch({headless:true,channel:'msedge'}),checks=[];
try{for(const width of [320,390,1366]){const p=await b.newPage({viewport:{width,height:900},reducedMotion:'no-preference'}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.route('**/*',r=>r.request().url().startsWith('http://127.0.0.1:')?r.continue():r.abort());await p.goto('http://127.0.0.1:'+server.address().port);
assert.equal(await p.locator('.scene-sprite').count(),11);const sprite=p.locator('.scene-cloud').first();const position=()=>sprite.evaluate(x=>getComputedStyle(x).transform);let before=await position();await p.waitForTimeout(250);assert.notEqual(await position(),before);
await p.screenshot({path:'.audit/scenery-map-'+width+'.png'});
const control=p.locator('.scene-toolbar .scene-toggle');await control.click();await p.waitForTimeout(50);before=await position();await p.waitForTimeout(250);assert.equal(await position(),before);assert.equal(await control.getAttribute('aria-pressed'),'false');
await p.reload();assert.equal(await control.getAttribute('aria-pressed'),'false');await control.click();assert.equal(await control.getAttribute('aria-pressed'),'true');
assert.equal(await p.locator('#particles').getAttribute('aria-hidden'),'true');assert.equal(await p.locator('#particles').evaluate(x=>getComputedStyle(x).pointerEvents),'none');
await p.locator('.continue-card').click();assert.equal(await p.locator('#video-screen').isVisible(),true);await p.locator('#video-start-btn').click();assert.equal(await p.locator('#quiz-screen').isVisible(),true);
assert.equal(await p.locator('.scene-butterfly').first().isVisible(),false);assert.equal(await sprite.isVisible(),true);assert.equal(await sprite.evaluate(x=>getComputedStyle(x).animationDuration),'140s');
const fit=await p.evaluate(()=>({width:document.documentElement.scrollWidth,viewport:innerWidth,bar:document.querySelector('.quiz-top .bar').getBoundingClientRect().width}));assert.ok(fit.width<=fit.viewport+2);assert.ok(fit.bar>=60);
await p.screenshot({path:'.audit/scenery-quiz-'+width+'.png'});await p.locator('.quiz-top .scene-toggle').click();assert.equal(await p.locator('.quiz-top .scene-toggle').getAttribute('aria-pressed'),'false');await p.locator('.quiz-top .scene-toggle').click();
await p.emulateMedia({reducedMotion:'reduce'});await p.waitForFunction(()=>document.querySelector('.quiz-top .scene-toggle').disabled);assert.equal(await sprite.evaluate(x=>getComputedStyle(x).animationName),'none');assert.equal(await p.locator('.quiz-top .scene-toggle').isDisabled(),true);await p.emulateMedia({reducedMotion:'no-preference'});await p.waitForFunction(()=>!document.querySelector('.quiz-top .scene-toggle').disabled);assert.equal(await p.locator('.quiz-top .scene-toggle').isDisabled(),false);
assert.deepEqual(errors,[]);checks.push({width,moving:true,pauseAndReload:true,controlsClickable:true,quietQuiz:true,reducedMotion:true,errors});await p.close();}
}finally{await b.close();server.close();}fs.writeFileSync('.audit/scenery-results.json',JSON.stringify(checks,null,2));console.log(JSON.stringify(checks,null,2));})().catch(e=>{console.error(e);process.exit(1)});
