const fs=require('fs'),http=require('http');const{chromium}=require('C:/Users/dangq/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
(async()=>{const s=http.createServer((q,r)=>{r.setHeader('Content-Type','text/html; charset=utf-8');r.end(fs.readFileSync('index.html'))});await new Promise(r=>s.listen(0,'127.0.0.1',r));const b=await chromium.launch({headless:true,channel:'msedge'});const p=await b.newPage({viewport:{width:390,height:844}});await p.route('**/*',r=>r.request().url().startsWith('http://127.0.0.1:')?r.continue():r.abort());await p.goto('http://127.0.0.1:'+s.address().port);await p.addStyleTag({content:'*,*::before,*::after{animation:none!important;transition:none!important}'});await p.evaluate(()=>window.confetti=()=>{});
const textProblems=await p.evaluate(()=>{const bad=[];for(const[name,bank]of[['normal',BANKS],['advanced',ADV]])for(const[code,fns]of Object.entries(bank))for(let i=0;i<fns.length;i++){currentQ=fns[i]();subs=[];reviewMode=false;showScreen('quiz-screen');paint();const btns=[...document.querySelectorAll('#q-body .pk')].filter(e=>e.scrollWidth>e.clientWidth+3);if(btns.length)bad.push({bank:name,code,index:i+1,labels:btns.slice(0,4).map(x=>x.textContent)});}return bad});
if(textProblems.length){await p.evaluate(x=>{currentQ=(x.bank==='normal'?BANKS:ADV)[x.code][x.index-1]();subs=[];paint()},textProblems[0]);await p.waitForTimeout(100);await p.screenshot({path:'.audit/option-overflow.png'});}
const mobileNavigation=await p.evaluate(()=>{goMap();return [...document.querySelectorAll('.bottomnav [data-nav],.bottomnav button')].map(x=>({text:x.innerText,label:x.getAttribute('aria-label')}))});
await p.evaluate(()=>{showScreen('profile-screen')});await p.screenshot({path:'.audit/profile-mobile.png'});
const missingMessage=await p.evaluate(()=>{startQuiz('b1');const before=document.getElementById('q-body').innerHTML;submitAnswer();return {unchanged:before===document.getElementById('q-body').innerHTML,alerts:document.querySelectorAll('[role=alert],[aria-live]').length};});
const reviewButton=await p.evaluate(()=>{quizQs=[generateQuestions('b1',1)[0]];quizHistory=[{idx:1,userAnswer:'wrong',question:'test',correctAnswer:quizQs[0].a,isCorrect:false}];retryQuiz();return [...document.querySelectorAll('#quiz-screen button')].filter(x=>x.getBoundingClientRect().width).map(x=>x.innerText)});
await p.addStyleTag({content:'#quiz-screen.active{justify-content:flex-start}.quiz-top,.q-card,.quiz-actions{flex-shrink:0}'});
const fixed=[];
for(const size of [{width:390,height:844},{width:1366,height:768},{width:390,height:500}]){await p.setViewportSize(size);const result=await p.evaluate(()=>{let all=0,bad=0;for(const bank of[BANKS,ADV])for(const fns of Object.values(bank))for(const fn of fns){currentQ=fn();subs=[];reviewMode=false;showScreen('quiz-screen');paint();const sc=document.getElementById('quiz-screen');sc.scrollTop=0;if(document.querySelector('.quiz-top').getBoundingClientRect().top<sc.getBoundingClientRect().top-4)bad++;all++;}return{all,bad}});fixed.push({size,...result})}
const out={textProblems,mobileNavigation,missingMessage,reviewButton,isolatedLayoutFix:fixed};fs.writeFileSync('.audit/ui-details.json',JSON.stringify(out,null,2));console.log(JSON.stringify({...out,textProblems:textProblems.slice(0,20),textProblemCount:textProblems.length},null,2));await b.close();s.close();})().catch(e=>{console.error(e);process.exit(1)});
